# github action to deploy api to azure

name: Deploy API to Azure

on:
    push:
        branches:
            - main

env:
    AZURE_WEB_APP_NAME: 'Cbc-Api-Test'
    AZURE_WEBAPP_PACKAGE_PATH: './publish'
    API_PUBLISH_SECRET: $${{ secrets.API_PUBLISH_SECRET }}
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x
            - name: Restore dependencies
              run: dotnet restore ./Template.API/CBC.API.csproj

            - name: Build
              run: dotnet build ./Template.API/CBC.API.csproj --configuration Release --no-restore

            - name: Test
              run: dotnet test ./Template.API/CBC.API.csproj --no-restore --verbosity normal

            - name: Publish
              run: dotnet publish ./Template.API/CBC.API.csproj --output ./publish

            - name: Deploy to azure
              uses: azure/webapps-deploy@v2
              with: 
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: $${{ secrets.API_PUBLISH_SECRET }}
                  package: ./publish

                
